import {
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { organization, user } from "./auth";

export const locations = pgTable("locations", {
  address: text("address"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  organizationId: text("organization_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
});

export const programs = pgTable("programs", {
  brandColor: text("brand_color").default("#18181b").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  id: text("id").primaryKey(),
  logoUrl: text("logo_url"),
  organizationId: text("organization_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  rewardLabel: text("reward_label").default("1 Récompense offerte").notNull(),
  stampsRequired: integer("stamps_required").default(10).notNull(),
  // Type can be 'stamps' or 'points'
  type: text("type").default("stamps").notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const rewards = pgTable("rewards", {
  cost: integer("cost").default(10).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  id: text("id").primaryKey(),
  label: text("label").notNull(),
  programId: text("program_id")
    .notNull()
    .references(() => programs.id, { onDelete: "cascade" }),
});

export const customers = pgTable(
  "customers",
  {
    createdAt: timestamp("created_at").defaultNow().notNull(),
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    organizationId: text("organization_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    phone: text("phone").notNull(),
  },
  (table) => [
    uniqueIndex("customers_org_phone_idx").on(
      table.organizationId,
      table.phone
    ),
  ]
);

export const cards = pgTable(
  "cards",
  {
    balance: integer("balance").default(0).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    customerId: text("customer_id")
      .notNull()
      .references(() => customers.id, { onDelete: "cascade" }),
    id: text("id").primaryKey(),
    programId: text("program_id")
      .notNull()
      .references(() => programs.id, { onDelete: "cascade" }),
    // Random, secret cryptographic token used in QR code
    token: text("token").notNull().unique(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("cards_customer_program_idx").on(
      table.customerId,
      table.programId
    ),
  ]
);

export const transactions = pgTable(
  "transactions",
  {
    amount: integer("amount").default(1).notNull(),
    cardId: text("card_id")
      .notNull()
      .references(() => cards.id, { onDelete: "cascade" }),
    // Unique UUID generated by device, prevents duplicate/double stamps
    clientUuid: text("client_uuid").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    id: text("id").primaryKey(),
    staffUserId: text("staff_user_id").references(() => user.id, {
      onDelete: "set null",
    }),
    // Type can be 'stamp', 'points', or 'reset'
    type: text("type").default("stamp").notNull(),
  },
  (table) => [uniqueIndex("transactions_client_uuid_idx").on(table.clientUuid)]
);

export const redemptions = pgTable("redemptions", {
  cardId: text("card_id")
    .notNull()
    .references(() => cards.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  id: text("id").primaryKey(),
  rewardId: text("reward_id").references(() => rewards.id, {
    onDelete: "set null",
  }),
  staffUserId: text("staff_user_id").references(() => user.id, {
    onDelete: "set null",
  }),
});

export const subscriptions = pgTable("subscriptions", {
  createdAt: timestamp("created_at").defaultNow().notNull(),
  id: text("id").primaryKey(),
  organizationId: text("organization_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  paidUntil: timestamp("paid_until").notNull(),
});
